server:
  port: 8083

spring:
  application:
    name: elm-user
  datasource:
    url: jdbc:mysql://localhost:3306/elm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456

jwt:
  secret: elmUserServiceSecretKey
  expiration: 86400000  # 24小时

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: yun.edu.user.pojo 