server:
  port: 9006

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elm?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC
    username: root
    password: root
  application:
    name: elm-rating

mybatis:
  type-aliases-package: yun.edu.rating.pojo
  configuration:
    map-underscore-to-camel-case: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
  circuitbreaker:
    enabled: true

resilience4j:
  circuitbreaker:
    configs:
      default:
        slidingWindowSize: 10
        permittedNumberOfCallsInHalfOpenState: 3
        waitDurationInOpenState: 5000
        failureRateThreshold: 50
    instances:
      orderService:
        baseConfig: default
      userService:
        baseConfig: default
      businessService:
        baseConfig: default 