server:
  port: 8090

spring:
  application:
    name: elm-gateway
  cloud:
    config:
      enabled: false
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        - id: elm-user
          uri: lb://elm-user
          predicates:
            - Path=/user/**
          filters:
            - StripPrefix=0
        - id: elm-business
          uri: lb://elm-business
          predicates:
            - Path=/business/**, /food/**
          filters:
            - StripPrefix=0
        - id: elm-order
          uri: lb://elm-order
          predicates:
            - Path=/orders/**, /cart/**
          filters:
            - StripPrefix=0
        - id: elm-delivery
          uri: lb://elm-delivery
          predicates:
            - Path=/deliveryAddress/**
          filters:
            - StripPrefix=0
        - id: elm-payment
          uri: lb://elm-payment
          predicates:
            - Path=/payment/**
          filters:
            - StripPrefix=0
        - id: elm-rating
          uri: lb://elm-rating
          predicates:
            - Path=/rating/**
          filters:
            - StripPrefix=0

# 添加日志配置
logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    org.springframework.http.server.reactive: DEBUG
    org.springframework.web.reactive: DEBUG
    reactor.netty: DEBUG
    redisratelimiter: DEBUG

# JWT配置
jwt:
  secret: elm-cloud-secure-jwt-secret-key-with-sufficient-length-for-hs256-algorithm
  expiration: 86400000  # 24小时

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    registry-fetch-interval-seconds: 3  # 缩短服务列表刷新间隔
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 5  # 心跳间隔
    lease-expiration-duration-in-seconds: 10  # 续约到期时间 