spring:
  application:
    name: elm-business
  # 禁用配置中心，直接使用本地配置
  cloud:
    config:
      enabled: false
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/elm?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource
  # Jackson配置
  jackson:
    default-property-inclusion: non_null
    serialization:
      fail-on-empty-beans: false

server:
  port: 8092

# MyBatis Plus配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    # 添加调试信息
    call-setters-on-nulls: true
    jdbc-type-for-null: 'NULL'
    default-executor-type: REUSE
    lazy-loading-enabled: false
  mapper-locations: classpath*:/mapper/**/*.xml
  type-aliases-package: yun.edu.business.entity

# MyBatis原生配置
mybatis:
  configuration:
    map-underscore-to-camel-case: true
    call-setters-on-nulls: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
    hostname: localhost

# 日志配置
logging:
  level:
    root: INFO
    yun.edu.business: DEBUG
    org.springframework.web: INFO
    org.hibernate: ERROR
    org.apache.ibatis: DEBUG
    java.sql: DEBUG 