server:
  port: 8888

spring:
  application:
    name: elm-config
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:./config-repo

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true 